#!/bin/bash

echo "-----Redirecionadores-----"
echo -e '\n1) > : redireciona a saída padrão de um comando para um arquivo,'
echo 'sobreescrevendo seu conteúdo caso o arquivo já exista, ou criando o arquivo caso'
echo 'ele não exista.'
echo -e '\n  Exemplo: ls > lista.txt'
echo -e '\n'
echo -e '\n2) 2> : redireciona a saída de erro de um comando para um arquivo,'
echo 'sobreescrevendo seu conteúdo caso o arquivo já exista, ou criando o arquivo caso'
echo 'ele não exista.'
echo -e '\n  Exemplo: sabendo que o arquivo abcd não existe, ls abcd 2> erro.txt'
echo -e '\n'
echo -e '\n3) &> : redireciona tanto a saída padrão quanto a saída de erro de um comando'
echo 'para um arquivo, sobreescrevendo seu conteúdo caso o arquivo já exista, ou criando'
echo 'o arquivo caso ele não exista.'
echo -e '\n Exemplo: ls 123 &> lista.txt'
echo -e '\n4) >> : redireciona a saída padrão de um comando para um arquivo, mantendo o'
echo 'conteúdo do mesmo e incrementando o novo conteúdo no final do arquivo.'
echo -e '\n Exemplo: ls >> lista.txt'
echo -e '\n'
echo -e '\n5) 2>> : redireciona a saída de erro de um comando para um arquivo. mantendo'
echo 'o conteúdo do mesmo e incrementando o novo conteúdo no final do arquivo.'
echo -e '\n Exemplo: sabendo que o arquivo abcd não existe, ls abcd 2>> erro.log'
echo -e '\n'
echo -e '\n 6) &>> : redireciona tanto a saída padrão quanto a saída de erro de um'
echo 'comando para um arquivo, mantendo o conteúdo do mesmo e incrementando o novo'
echo 'conteúdo no final do arquivo.'
echo -e '\n Exemplo: ls 123 &>> lista.txt'
echo -e '\n'
echo -e '\n7) < : redireciona a entrada padrão de um comando para um arquivo.'
echo -e '\n Exemplo: um arquivo chamado conta.txt contém o seguinte texto: "2.1 + 2.1",'
echo ' ao usarmos o comando "bc < conta.txt", inves do comando bc usar o teclado como'
echo ' entrada padrão, ele usará o arquivo conta.txt, e retornará a resolução da'
echo ' expressão númerica contida no arquivo, ou seja, 4.2.'
echo -e '\n'
echo -e '\n8) << : redireciona a entrada padrão de um comando para uma string digitada'
echo ' pelo usuário após a execução do comando, ele continuará lendo tudo que o usuário'
echo ' digita até que o mesmo digite a string especificada após o << no comando.'
echo -e '\n Exemplo: ao usarmos o comando "wc -l<< FIM", o comando começará a ler tudo'
echo ' que o usuário digitar e redirecionar para a entrada padrão do comando wc -l,'
echo ' e após o usuário digitar FIM, ele irá parar de ler e executará o comando.'
echo -e '\n'
echo -e '\n9) <<< : redireciona a entrada padrão de um comando para uma string'
echo -e '\n Exemplo: ao usarmos o comando bc <<< "2.1+2.1", o comando retornará 4.2'
echo -e '\n'
echo -e '\n10) | : redireciona a saída padrão de um comando para a entrada padrão de'
echo 'outro comando.'
echo -e '\n Exemplo: echo "oi" | tr 'o' 'x' , o comando retornará "xi" pois ele'
echo ' redirecionou a saída do comando "echo "oi"" para a entrada do comando'
echo  ' "tr 'o' 'x'" que substituiu as ocorrencias da letra o na string com letras x.'